# Generated by Django 5.0.6 on 2024-06-26 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_remark_created_at_alter_remark_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="remark",
            name="id",
        ),
        migrations.AlterField(
            model_name="remark",
            name="name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="input_infos",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
